AllCops:
  TargetRubyVersion: 2.0

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'test/**/*.rb'

Lint/DuplicateMethods:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Exclude:
    - 'test/transferwise_bank_test.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
